#!/usr/bin/env bash

# Author Jimmy MG Lim <mirageglobe@gmail.com>

# ----- common functions

yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { "$@" || die "cannot $*"; }

# ----- local functions

printHeader() {
  echo "*** -----"
  echo "*** Samurai v2"
  echo "*** -----"

}

printHelp() {
  echo "*** USAGE :"
  echo "    $0                                 # help"
  echo "    $0 help                            # help"
  echo "    $0 ui                              # ui"
  echo "    $0 <yaml file> <command number>    # run custom script file"
  echo "    $0 <commandnumber>                 # run command"
  echo "*** EXAMPLES :"
  echo "    $0 ui"
  echo "    $0 1"
}

runScript() {
  echo "hello"
}

# ----- check arguments

EXPECTED_ARGS=1
E_BADARGS=65

if [ "$#" -lt "$EXPECTED_ARGS" ]; then
  printHeader
  printHelp $0
  exit $E_BADARGS
fi

# ----- main functions

# Core UI Options
#Set UI_CMD_<command number> = <bash command> <command definition>
UI_CMD_0=( "Exit Samurai" "clear")
UI_CMD_1=( "Update Samurai" "curl -L https://raw.githubusercontent.com/mirageglobe/samurai/master/samurai/install.sh | bash" )
UI_CMD_2=( "Remove Samurai" "sudo rm /usr/local/bin/samurai && sudo rm /usr/local/bin/samurai-mac.py && sudo rm /usr/local/bin/samurai-linux.py" )
UI_CMD_3=( "Toggle ShowCmd mode" "" )
UI_CMD_4=( "Clear screen and show menu" "clear" )

UI_CMD_10=( "Change my login password" "passwd" )
UI_CMD_11=( "Update ubuntu and cleanup cache" "sudo apt-get update && sudo apt-get upgrade && sudo apt-get autoclean && sudo apt-get autoremove" )
UI_CMD_12=( "Update ubuntu distribution" "sudo apt-get dist-upgrade" )
UI_CMD_13=( "Install build-essential" "sudo apt-get install build-essential" )
UI_CMD_14=( "Add virtualbox guest additions for ubuntu (for virtualbox *buntu VMs)" "sudo apt-get install virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11" )
UI_CMD_15=( "Show users list" "column -ts: /etc/passwd | sort" )
UI_CMD_16=( "Restart shell" "exec \$SHELL -l" )
UI_CMD_17=( "Show IP address" "curl http://icanhazip.com" )
UI_CMD_18=( "Show disk space" "df -h --total" )
UI_CMD_19=( "Show kernel build information" "uname -a" )
UI_CMD_20=( "Show ubuntu or *buntu-like version information" "lsb_release -a" )
UI_CMD_21=( "Show open ports and listening apps" "netstat -lnptu" )
UI_CMD_22=( "Show local SMB/CIFS shares on network" "nmblookup -S '*'" )
UI_CMD_23=( "Show local mounted or mapped drives" "df" )
UI_CMD_24=( "Show memory, cache and swap" "egrep --color 'Mem|Cache|Swap' /proc/meminfo" )
UI_CMD_25=( "Setup Ubuntu Auto Upgrade (Ubuntu Recommended)" "sudo apt-get install unattended-upgrades && dpkg-reconfigure --priority=low unattended-upgrades" )

SK_CMD=$1
SK_OPT=$2

case "$SK_CMD" in
  help)
    echo "Help options"
    printHelp $0
    ;;
  ui)
    printHeader
    # runs ui_cmd with $2 and array 0 which is the command; see declare core ui options
    SK_CMD_CMD=$(eval echo \${UI_CMD_$SK_OPT[0]})
    SK_CMD_DESC=$(eval echo \${UI_CMD_$SK_OPT[1]})

    echo "    Executing :: $SK_CMD_CMD"
    eval $SK_CMD_DESC
    ;;
  *)
    die
esac

